### ISSUE TITLE
secp384r1 recommended but not secp521r1?

### ISSUE THREAD

**Issue by konstruktoid** [nsacyber/Mitigating-Obsolete-TLS#8]
Is there any reason `secp384r1` is recommended but `secp521r1` isn't?

```
$ openssl version && openssl ecparam -list_curves | grep -E 'secp.*r1' | sort -r
OpenSSL 1.1.1i  8 Dec 2020
  secp521r1 : NIST/SECG curve over a 521 bit prime field
  secp384r1 : NIST/SECG curve over a 384 bit prime field
  secp224r1 : NIST/SECG curve over a 224 bit prime field
  secp160r1 : SECG curve over a 160 bit prime field
  secp128r1 : SECG curve over a 128 bit prime field
  secp112r1 : SECG/WTLS curve over a 112 bit prime field
```

_Originally posted by @konstruktoid in https://github.com/nsacyber/Mitigating-Obsolete-TLS/issues/7#issuecomment-760069167_

**Comment by ajlaing** [comment]
secp-521r1 is allowed under both CNSS and interoperability configurations. Since it is not required to be supported, and might introduce interoperability or performance concerns, we did not specifically mention it.

**Comment by konstruktoid** [comment]
Thanks for the reply @ajlaing

**Comment by briansmith** [comment]
@ajlaing wrote:
> secp-521r1 is allowed under both CNSS and interoperability configurations.

I did not realize secp521r1 is allowed under CNSS. Could you please share a link to the guidance that says secp521r1 is allowed? It would be important for some vendors who want to have an allowed backup to P-384, e.g. in case their P-384 implementation needs to be disabled for some reason. Thanks!

**Comment by ajlaing** [comment]
No backup is needed. Additional guidance regarding secp521r1 is forthcoming.

**Comment by briansmith** [comment]
> No backup is needed.

Let's say I had a bug in my P-384 implementation that I couldn't fix fast enough. It would be nice to recommend to customers to disable P-384 and use P-521 until the fix can be developed and deployed. That's the kind of scenerio for which I'm looking for a backup.
